#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTV")]
	public partial class qltv1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdocgia(docgia instance);
    partial void Updatedocgia(docgia instance);
    partial void Deletedocgia(docgia instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertnhaxuatban(nhaxuatban instance);
    partial void Updatenhaxuatban(nhaxuatban instance);
    partial void Deletenhaxuatban(nhaxuatban instance);
    partial void Insertphiemmuontra(phiemmuontra instance);
    partial void Updatephiemmuontra(phiemmuontra instance);
    partial void Deletephiemmuontra(phiemmuontra instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    partial void Inserttacgia(tacgia instance);
    partial void Updatetacgia(tacgia instance);
    partial void Deletetacgia(tacgia instance);
    partial void Inserttheloai(theloai instance);
    partial void Updatetheloai(theloai instance);
    partial void Deletetheloai(theloai instance);
    #endregion
		
		public qltv1DataContext() : 
				base(global::QLTHUVIEN.Properties.Settings.Default.QLTVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qltv1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qltv1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qltv1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qltv1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<docgia> docgias
		{
			get
			{
				return this.GetTable<docgia>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<nhaxuatban> nhaxuatbans
		{
			get
			{
				return this.GetTable<nhaxuatban>();
			}
		}
		
		public System.Data.Linq.Table<phiemmuontra> phiemmuontras
		{
			get
			{
				return this.GetTable<phiemmuontra>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
		
		public System.Data.Linq.Table<tacgia> tacgias
		{
			get
			{
				return this.GetTable<tacgia>();
			}
		}
		
		public System.Data.Linq.Table<theloai> theloais
		{
			get
			{
				return this.GetTable<theloai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.docgia")]
	public partial class docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDocGia;
		
		private string _HoTenDG;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _DiaChi;
		
		private EntitySet<phiemmuontra> _phiemmuontras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnHoTenDGChanging(string value);
    partial void OnHoTenDGChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public docgia()
		{
			this._phiemmuontras = new EntitySet<phiemmuontra>(new Action<phiemmuontra>(this.attach_phiemmuontras), new Action<phiemmuontra>(this.detach_phiemmuontras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenDG", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HoTenDG
		{
			get
			{
				return this._HoTenDG;
			}
			set
			{
				if ((this._HoTenDG != value))
				{
					this.OnHoTenDGChanging(value);
					this.SendPropertyChanging();
					this._HoTenDG = value;
					this.SendPropertyChanged("HoTenDG");
					this.OnHoTenDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_phiemmuontra", Storage="_phiemmuontras", ThisKey="MaDocGia", OtherKey="MaDocGia")]
		public EntitySet<phiemmuontra> phiemmuontras
		{
			get
			{
				return this._phiemmuontras;
			}
			set
			{
				this._phiemmuontras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.docgia = this;
		}
		
		private void detach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.docgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _HoTenNV;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _DiaChi;
		
		private string _SoDTNV;
		
		private EntitySet<phiemmuontra> _phiemmuontras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnHoTenNVChanging(string value);
    partial void OnHoTenNVChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTNVChanging(string value);
    partial void OnSoDTNVChanged();
    #endregion
		
		public nhanvien()
		{
			this._phiemmuontras = new EntitySet<phiemmuontra>(new Action<phiemmuontra>(this.attach_phiemmuontras), new Action<phiemmuontra>(this.detach_phiemmuontras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenNV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HoTenNV
		{
			get
			{
				return this._HoTenNV;
			}
			set
			{
				if ((this._HoTenNV != value))
				{
					this.OnHoTenNVChanging(value);
					this.SendPropertyChanging();
					this._HoTenNV = value;
					this.SendPropertyChanged("HoTenNV");
					this.OnHoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDTNV", DbType="VarChar(20)")]
		public string SoDTNV
		{
			get
			{
				return this._SoDTNV;
			}
			set
			{
				if ((this._SoDTNV != value))
				{
					this.OnSoDTNVChanging(value);
					this.SendPropertyChanging();
					this._SoDTNV = value;
					this.SendPropertyChanged("SoDTNV");
					this.OnSoDTNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phiemmuontra", Storage="_phiemmuontras", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<phiemmuontra> phiemmuontras
		{
			get
			{
				return this._phiemmuontras;
			}
			set
			{
				this._phiemmuontras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhaxuatban")]
	public partial class nhaxuatban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhaXB;
		
		private string _TenNhaXB;
		
		private string _DiaChi;
		
		private string _SoDTXB;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhaXBChanging(string value);
    partial void OnMaNhaXBChanged();
    partial void OnTenNhaXBChanging(string value);
    partial void OnTenNhaXBChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTXBChanging(string value);
    partial void OnSoDTXBChanged();
    #endregion
		
		public nhaxuatban()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaXB", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhaXB
		{
			get
			{
				return this._MaNhaXB;
			}
			set
			{
				if ((this._MaNhaXB != value))
				{
					this.OnMaNhaXBChanging(value);
					this.SendPropertyChanging();
					this._MaNhaXB = value;
					this.SendPropertyChanged("MaNhaXB");
					this.OnMaNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhaXB
		{
			get
			{
				return this._TenNhaXB;
			}
			set
			{
				if ((this._TenNhaXB != value))
				{
					this.OnTenNhaXBChanging(value);
					this.SendPropertyChanging();
					this._TenNhaXB = value;
					this.SendPropertyChanged("TenNhaXB");
					this.OnTenNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDTXB", DbType="VarChar(20)")]
		public string SoDTXB
		{
			get
			{
				return this._SoDTXB;
			}
			set
			{
				if ((this._SoDTXB != value))
				{
					this.OnSoDTXBChanging(value);
					this.SendPropertyChanging();
					this._SoDTXB = value;
					this.SendPropertyChanged("SoDTXB");
					this.OnSoDTXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaxuatban_sach", Storage="_saches", ThisKey="MaNhaXB", OtherKey="MaNhaXB")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nhaxuatban = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nhaxuatban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phiemmuontra")]
	public partial class phiemmuontra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieu;
		
		private System.Nullable<System.DateTime> _NgayMuon;
		
		private System.Nullable<System.DateTime> _NgayHenTra;
		
		private string _MaSach;
		
		private string _MaDocGia;
		
		private string _MaNhanVien;
		
		private string _TinhTrangSach;
		
		private EntityRef<docgia> _docgia;
		
		private EntityRef<nhanvien> _nhanvien;
		
		private EntityRef<sach> _sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuChanging(string value);
    partial void OnMaPhieuChanged();
    partial void OnNgayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuonChanged();
    partial void OnNgayHenTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHenTraChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTinhTrangSachChanging(string value);
    partial void OnTinhTrangSachChanged();
    #endregion
		
		public phiemmuontra()
		{
			this._docgia = default(EntityRef<docgia>);
			this._nhanvien = default(EntityRef<nhanvien>);
			this._sach = default(EntityRef<sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHenTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHenTra
		{
			get
			{
				return this._NgayHenTra;
			}
			set
			{
				if ((this._NgayHenTra != value))
				{
					this.OnNgayHenTraChanging(value);
					this.SendPropertyChanging();
					this._NgayHenTra = value;
					this.SendPropertyChanged("NgayHenTra");
					this.OnNgayHenTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					if (this._docgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TinhTrangSach
		{
			get
			{
				return this._TinhTrangSach;
			}
			set
			{
				if ((this._TinhTrangSach != value))
				{
					this.OnTinhTrangSachChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangSach = value;
					this.SendPropertyChanged("TinhTrangSach");
					this.OnTinhTrangSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_phiemmuontra", Storage="_docgia", ThisKey="MaDocGia", OtherKey="MaDocGia", IsForeignKey=true)]
		public docgia docgia
		{
			get
			{
				return this._docgia.Entity;
			}
			set
			{
				docgia previousValue = this._docgia.Entity;
				if (((previousValue != value) 
							|| (this._docgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._docgia.Entity = null;
						previousValue.phiemmuontras.Remove(this);
					}
					this._docgia.Entity = value;
					if ((value != null))
					{
						value.phiemmuontras.Add(this);
						this._MaDocGia = value.MaDocGia;
					}
					else
					{
						this._MaDocGia = default(string);
					}
					this.SendPropertyChanged("docgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phiemmuontra", Storage="_nhanvien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.phiemmuontras.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.phiemmuontras.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_phiemmuontra", Storage="_sach", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public sach sach
		{
			get
			{
				return this._sach.Entity;
			}
			set
			{
				sach previousValue = this._sach.Entity;
				if (((previousValue != value) 
							|| (this._sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sach.Entity = null;
						previousValue.phiemmuontras.Remove(this);
					}
					this._sach.Entity = value;
					if ((value != null))
					{
						value.phiemmuontras.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _NamXB;
		
		private string _MaNhaXB;
		
		private string _MaTheLoai;
		
		private string _MaTacGia;
		
		private EntitySet<phiemmuontra> _phiemmuontras;
		
		private EntityRef<nhaxuatban> _nhaxuatban;
		
		private EntityRef<tacgia> _tacgia;
		
		private EntityRef<theloai> _theloai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnNamXBChanging(string value);
    partial void OnNamXBChanged();
    partial void OnMaNhaXBChanging(string value);
    partial void OnMaNhaXBChanged();
    partial void OnMaTheLoaiChanging(string value);
    partial void OnMaTheLoaiChanged();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    #endregion
		
		public sach()
		{
			this._phiemmuontras = new EntitySet<phiemmuontra>(new Action<phiemmuontra>(this.attach_phiemmuontras), new Action<phiemmuontra>(this.detach_phiemmuontras));
			this._nhaxuatban = default(EntityRef<nhaxuatban>);
			this._tacgia = default(EntityRef<tacgia>);
			this._theloai = default(EntityRef<theloai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(40)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this.OnNamXBChanging(value);
					this.SendPropertyChanging();
					this._NamXB = value;
					this.SendPropertyChanged("NamXB");
					this.OnNamXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaXB", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNhaXB
		{
			get
			{
				return this._MaNhaXB;
			}
			set
			{
				if ((this._MaNhaXB != value))
				{
					if (this._nhaxuatban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhaXBChanging(value);
					this.SendPropertyChanging();
					this._MaNhaXB = value;
					this.SendPropertyChanged("MaNhaXB");
					this.OnMaNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaTheLoai
		{
			get
			{
				return this._MaTheLoai;
			}
			set
			{
				if ((this._MaTheLoai != value))
				{
					if (this._theloai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoai = value;
					this.SendPropertyChanged("MaTheLoai");
					this.OnMaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					if (this._tacgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_phiemmuontra", Storage="_phiemmuontras", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<phiemmuontra> phiemmuontras
		{
			get
			{
				return this._phiemmuontras;
			}
			set
			{
				this._phiemmuontras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaxuatban_sach", Storage="_nhaxuatban", ThisKey="MaNhaXB", OtherKey="MaNhaXB", IsForeignKey=true)]
		public nhaxuatban nhaxuatban
		{
			get
			{
				return this._nhaxuatban.Entity;
			}
			set
			{
				nhaxuatban previousValue = this._nhaxuatban.Entity;
				if (((previousValue != value) 
							|| (this._nhaxuatban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhaxuatban.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._nhaxuatban.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._MaNhaXB = value.MaNhaXB;
					}
					else
					{
						this._MaNhaXB = default(string);
					}
					this.SendPropertyChanged("nhaxuatban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tacgia_sach", Storage="_tacgia", ThisKey="MaTacGia", OtherKey="MaTacGia", IsForeignKey=true)]
		public tacgia tacgia
		{
			get
			{
				return this._tacgia.Entity;
			}
			set
			{
				tacgia previousValue = this._tacgia.Entity;
				if (((previousValue != value) 
							|| (this._tacgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tacgia.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._tacgia.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._MaTacGia = value.MaTacGia;
					}
					else
					{
						this._MaTacGia = default(string);
					}
					this.SendPropertyChanged("tacgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="theloai_sach", Storage="_theloai", ThisKey="MaTheLoai", OtherKey="MaTheLoai", IsForeignKey=true)]
		public theloai theloai
		{
			get
			{
				return this._theloai.Entity;
			}
			set
			{
				theloai previousValue = this._theloai.Entity;
				if (((previousValue != value) 
							|| (this._theloai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._theloai.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._theloai.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._MaTheLoai = value.MaTheLoai;
					}
					else
					{
						this._MaTheLoai = default(string);
					}
					this.SendPropertyChanged("theloai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.sach = this;
		}
		
		private void detach_phiemmuontras(phiemmuontra entity)
		{
			this.SendPropertyChanging();
			entity.sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tacgia")]
	public partial class tacgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTacGia;
		
		private string _HoTenTG;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    partial void OnHoTenTGChanging(string value);
    partial void OnHoTenTGChanged();
    #endregion
		
		public tacgia()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenTG", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HoTenTG
		{
			get
			{
				return this._HoTenTG;
			}
			set
			{
				if ((this._HoTenTG != value))
				{
					this.OnHoTenTGChanging(value);
					this.SendPropertyChanging();
					this._HoTenTG = value;
					this.SendPropertyChanged("HoTenTG");
					this.OnHoTenTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tacgia_sach", Storage="_saches", ThisKey="MaTacGia", OtherKey="MaTacGia")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tacgia = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tacgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.theloai")]
	public partial class theloai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTheLoai;
		
		private string _TenTheLoai;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTheLoaiChanging(string value);
    partial void OnMaTheLoaiChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    #endregion
		
		public theloai()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoai", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTheLoai
		{
			get
			{
				return this._MaTheLoai;
			}
			set
			{
				if ((this._MaTheLoai != value))
				{
					this.OnMaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoai = value;
					this.SendPropertyChanged("MaTheLoai");
					this.OnMaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(40)")]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="theloai_sach", Storage="_saches", ThisKey="MaTheLoai", OtherKey="MaTheLoai")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.theloai = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.theloai = null;
		}
	}
}
#pragma warning restore 1591
